// =============================================================================
// CROWNFALL — Master Database Set ALPHA (290 Carte Uniche)
// Formato per Antigravity & crownfall.html (v4.7+)
// =============================================================================

const CARDS_ALPHA = {
  // =========================================================================
  // 1. BASTIONE DI FERRO (38 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE (5)
  "Baluardo di Granito Vivente": { faction: "Ferro", glyph: "🏰", shortName: "GRANITO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 7, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. 7 PV. Massiccio: immune a spinte. Copertura: -2 danni fisici adiacenti." },
  "Altare della Fortezza": { faction: "Ferro", glyph: "🛡️", shortName: "FORTEZZA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 7, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Alleati adiacenti infliggono +1 danno extra durante il contrattacco." },
  "Torretta di Ferro Fuso": { faction: "Ferro", glyph: "🗼", shortName: "TORRETTA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 1, move: "none", gittata: 2, rarity: "U", isMiniature: false, desc: "+1 Mana. Contrattacca a distanza 2 se un alleato adiacente subisce attacchi ortogonali." },
  "Fossa dei Picchieri": { faction: "Ferro", glyph: "🕳️", shortName: "FOSSA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Nemici che muovono adiacenti a questa struttura subiscono 1 danno immediato." },
  "Contrafforte di Trincea": { faction: "Ferro", glyph: "🧱", shortName: "CONTRAFF.", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Assorbe 1 danno subito da un alleato adiacente trasferendolo su di sé." },

  // FANTERIA 1M (6)
  "Fante Corazzato": { faction: "Ferro", glyph: "🛡️", shortName: "FANTE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Armatura: riduce di -1 ogni danno fisico subito (minimo 1)." },
  "Fante con Scudo a Torre": { faction: "Ferro", glyph: "🚪", shortName: "SCUDO TORRE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Interposizione: i tiri a distanza nemici contro alleati adiacenti deviano su di lui." },
  "Recluta con Brocchiero": { faction: "Ferro", glyph: "🛡️", shortName: "BROCCHIERO", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Ha 1 armatura temporanea solo nel primo round in cui subisce un attacco." },
  "Sentinella del Bastione": { faction: "Ferro", glyph: "🏰", shortName: "SENT. BAST.", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Presidio: non attacca attivamente; contrattacca a 2 ATT solo se colpita in mischia." },
  "Picchiere di Presidio": { faction: "Ferro", glyph: "🔱", shortName: "PICCA PRES.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Allungo: attacca a 2 caselle senza contrattacco; muove solo avanti o indietro." },
  "Guardia alla Porta": { faction: "Ferro", glyph: "🗝️", shortName: "G. PORTA", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "I nemici non possono attraversare le caselle ortogonalmente adiacenti a lui." },

  // SPECIALISTI 2-3M (11)
  "Balestriere della Guardia": { faction: "Ferro", glyph: "🏹", shortName: "BALESTR. G.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 2, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Tiro Coperto: Gittata 2 senza contrattacco; non contrattacca in mischia." },
  "Picchiere della Guardia": { faction: "Ferro", glyph: "🔱", shortName: "PICCHIERE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Allungo: colpisce a 2 caselle in linea retta senza subire contrattacco difensivo." },
  "Alabardiere da Trincea": { faction: "Ferro", glyph: "🪓", shortName: "ALABARDA", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Allungo & Flanking: infligge 3 danni anziché 2 se attacca con Aggiramento." },
  "Fante Corazzato Veterano": { faction: "Ferro", glyph: "🛡️", shortName: "FANTE VET.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Muro di Scudi: alleati e Altari adiacenti sono immuni a danni da impatto contro ostacoli." },
  "Guardia Giurata di Ferro": { faction: "Ferro", glyph: "⚔️", shortName: "G. GIURATA", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Ottiene +1 ATT se si trova a 2 o meno passi dal Comandante alleato." },
  "Genio Ferriere": { faction: "Ferro", glyph: "🔧", shortName: "GENIO", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "[1 Azione]: ripara 2 PV a una struttura o Altare adiacente." },
  "Cavaliere Corazzato": { faction: "Ferro", glyph: "🐎", shortName: "CAV. CORAZ.", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: salta ostacoli; se atterra adiacente a un nemico lo spinge di 1 casella." },
  "Lanciere da Breccia": { faction: "Ferro", glyph: "🏇", shortName: "LANCIERE B.", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "knight", gittata: 2, rarity: "U", isMiniature: true, desc: "Balzo a L & Gittata 2 ortogonale: attacca a distanza senza contrattacco." },
  "Scudiero d'Ossidiana": { faction: "Ferro", glyph: "🛡️", shortName: "SCUD. OSS.", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Assorbe la metà del danno inflitto al Comandante se gli è adiacente." },
  "Campione del Bastione": { faction: "Ferro", glyph: "🎖️", shortName: "CAMPIONE", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Contrattacca a 4 ATT se i suoi PV scendono a 2 o meno." },
  "Mastro d'Armi di Ferro": { faction: "Ferro", glyph: "⚒️", shortName: "MASTRO FERRO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Le truppe alleate adiacenti con armatura infliggono +1 danno in mischia." },

  // COLOSSI 4+M (5)
  "Ariete da Breccia": { faction: "Ferro", glyph: "🪵", shortName: "ARIETE", cost: 4, type: "unit", slot: "HEAVY", att: 2, pv: 6, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Sfondamento: 6 danni ad Altari e muri. Respinge i pezzi (+2 danni se urtano)." },
  "Ariete Spaccagranito": { faction: "Ferro", glyph: "🪨", shortName: "SPACCAGRAN.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 7, move: "ortho2", gittata: 1, rarity: "R", isMiniature: true, desc: "Frattura: distruggendo un Altare crea una Voragine permanente impassabile." },
  "Balista Corazzata": { faction: "Ferro", glyph: "🎯", shortName: "BALISTA C.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 4, move: "ortho", gittata: 3, rarity: "R", isMiniature: true, desc: "Gittata 3: tiro in linea retta senza contrattacco; infligge 4 danni a strutture." },
  "Carro di Trincea": { faction: "Ferro", glyph: "🚜", shortName: "CARRO TRIN.", cost: 3, type: "unit", slot: "HEAVY", att: 1, pv: 6, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Copertura Mobile: le caselle retrostanti sono protette contro tiri a distanza." },
  "Titano della Porta": { faction: "Ferro", glyph: "🚪", shortName: "TITANO PORTA", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 9, move: "ortho", gittata: 1, rarity: "M", isMiniature: true, desc: "Inespugnabile: immune a spinte e sortilegi diretti. Blocca il transito nemico attorno a sé." },

  // SORTILEGI & REAZIONI (11)
  "Comando di Trincea": { faction: "Ferro", glyph: "🛡️", shortName: "TRINCEA", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Comandante e alleati adiacenti ad Altari azzerano i danni a distanza per 1 round." },
  "Manto d'Ossidiana": { faction: "Ferro", glyph: "🖤", shortName: "MANTO OSS.", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "2 alleati diventano immuni a spinte, trascinamenti e danni urto fino al prossimo turno." },
  "Formazione a Testuggine": { faction: "Ferro", glyph: "🐢", shortName: "TESTUGGINE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Alleati adiacenti tra loro ottengono +1 armatura; non possono muovere in questo turno." },
  "Carica d'Acciaio": { faction: "Ferro", glyph: "⚡", shortName: "CARICA ACC.", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Un'unità con armatura muove di 1 casella extra a costo 0 Azioni e spinge ostacoli." },
  "Rinforzo dei Plinti": { faction: "Ferro", glyph: "🧱", shortName: "RINFORZO", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Ripristina 3 PV a un Altare alleato o conferisce 3 PV temporanei a una struttura." },
  "Sfondamento di Linea": { faction: "Ferro", glyph: "💥", shortName: "SFONDAMENTO", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Il prossimo attacco alleato ignora coperture difensive e spinge indietro il difensore." },
  "Frantumare la Corazza": { faction: "Ferro", glyph: "🔨", shortName: "FRANT. COR.", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Rimuove permanentemente armature e scudi passivi da un nemico entro 3 passi." },
  "Scudo d'Ossidiana": { faction: "Ferro", glyph: "✨", shortName: "SCUDO OSS.", cost: 1, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Cura 3 PV al Comandante e conferisce Scudo Totale contro il prossimo colpo subito." },
  "Interdizione di Bastione": { faction: "Ferro", glyph: "🚫", shortName: "INTERD. BAST.", cost: 2, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "I nemici non possono attraversare una specifica riga con movimenti lineari nel prossimo round." },
  "Muro d'Acciaio": { faction: "Ferro", glyph: "🪞", shortName: "MURO ACC.", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: azzera completamente il danno di un attacco a distanza nemico." },
  "Ritorsione dello Scudo": { faction: "Ferro", glyph: "🛡️", shortName: "RITORSIONE", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione su attacco mischia: riduce il danno di 2 e infligge 2 danni all'attaccante." },

  // =========================================================================
  // 2. ROGO DELLE CENERI (38 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE (5)
  "Sepolcro delle Ceneri Calde": { faction: "Ceneri", glyph: "⚰️", shortName: "SEPOLCRO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Se distrutto, genera +2 Segnalini Sangue per te anziché zero." },
  "Altare del Sepolcro": { faction: "Ceneri", glyph: "🪦", shortName: "ALT. SEPOLCRO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Quando un alleato muore adiacente a questo Altare, incassi +1 Sangue extra." },
  "Pira dell'Anima": { faction: "Ceneri", glyph: "🔥", shortName: "PIRA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Sacrificando volontariamente questa struttura ottieni 3 Sangue immediati." },
  "Cripta dei Condannati": { faction: "Ceneri", glyph: "🚪", shortName: "CRIPTA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Consente di schierare truppe a costo 1 Mana adiacenti ad essa." },
  "Focolare delle Braci Spente": { faction: "Ceneri", glyph: "🌋", shortName: "FOCOLARE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Quando un'unità muore entro 2 caselle, infligge 1 danno al nemico più vicino." },

  // FANTERIA 1M (6)
  "Guscio Esplosivo": { faction: "Ceneri", glyph: "💣", shortName: "GUSCIO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Detonazione: alla morte infligge 2 danni a tutte le 4 caselle ortogonali adiacenti." },
  "Kamikaze di Braci": { faction: "Ceneri", glyph: "🧨", shortName: "KAMIKAZE", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Scoppio Frontale: alla morte infligge 3 danni alla casella esattamente frontale." },
  "Spirito Vagante": { faction: "Ceneri", glyph: "👻", shortName: "SPIRITO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 1, move: "diag", gittata: 1, slancio: true, rarity: "C", isMiniature: true, desc: "Slancio Diagonale: entra, muove lungo le diagonali e attacca subito." },
  "Cane delle Fosse": { faction: "Ceneri", glyph: "🐕", shortName: "CANE FOSSE", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 1, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Sciame: ottiene +1 ATT se attacca assieme a un altro Cane delle Fosse." },
  "Carogna Rianimata": { faction: "Ceneri", glyph: "🧟", shortName: "CAROGNA", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Se distrutta da un attacco a distanza, non fornisce Sangue all'uccisore." },
  "Verme Sepolcrale": { faction: "Ceneri", glyph: "🪱", shortName: "VERME SEP.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Alla morte genera 1 Sangue extra per il controllore." },

  // SPECIALISTI 2-3M (11)
  "Ghoul Dissotterrato": { faction: "Ceneri", glyph: "🧟", shortName: "GHOUL", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 2, move: "knight", gittata: 1, slancio: true, rarity: "U", isMiniature: true, desc: "Slancio & Balzo a L: salta ostacoli e attacca subito nel turno di ingresso." },
  "Ombra delle Fosse": { faction: "Ceneri", glyph: "👤", shortName: "OMBRA", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Imboscata: ottiene Slancio se entra dove è morta un'unità in questo round." },
  "Banshee delle Ceneri": { faction: "Ceneri", glyph: "👻", shortName: "BANSHEE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "diag", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2 diagonale: spara a 2 caselle diagonali ignorando armature fisiche." },
  "Masticatore di Ossa": { faction: "Ceneri", glyph: "🦷", shortName: "MASTICAT.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "[1 Azione]: distrugge un alleato con 1 PV per ripristinare interamente la propria salute." },
  "Sacerdote del Rogo": { faction: "Ceneri", glyph: "🧙", shortName: "SACERDOTE", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Quando lanci un sortilegio che spende Sangue, infligge 1 danno al Comandante nemico." },
  "Spettro Vorace": { faction: "Ceneri", glyph: "🦇", shortName: "SPETTRO", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 2, move: "omni", gittata: 1, rarity: "U", isMiniature: true, desc: "Passo Etereo: attraversa unità amiche e nemiche durante il movimento." },
  "Urlatore delle Catacombe": { faction: "Ceneri", glyph: "🗣️", shortName: "URLATORE", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Gittata 2: quando colpisce un nemico, gli impedisce di contrattaccare per il turno." },
  "Flagellatore di Braci": { faction: "Ceneri", glyph: "🔥", shortName: "FLAGELLAT.", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "diag", gittata: 1, rarity: "U", isMiniature: true, desc: "Spine di cenere: infligge 1 danno riflesso a chiunque lo colpisca in mischia." },
  "Rianimatore Sepolcrale": { faction: "Ceneri", glyph: "🪦", shortName: "RIANIMAT.", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 5, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "[1 Azione + 2 Sangue]: schiera un Guscio Esplosivo su una casella libera adiacente." },
  "Cavaliere del Sudario": { faction: "Ceneri", glyph: "🏇", shortName: "CAV. SUDARIO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: ottiene +1 ATT se attacca bersagli che hanno già subito danni nel round." },
  "Necromante Minore": { faction: "Ceneri", glyph: "💀", shortName: "NECROMANTE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: se distrugge un pezzo nemico, incassi +1 Sangue addizionale." },

  // COLOSSI 4+M (5)
  "Necro-Abominio": { faction: "Ceneri", glyph: "🧟‍♂️", shortName: "ABOMINIO", cost: 4, type: "unit", slot: "HEAVY", att: 4, pv: 6, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Banchetto: recupera 2 PV ogni volta che distrugge un pezzo nemico in combattimento." },
  "Colosso di Cadaveri": { faction: "Ceneri", glyph: "🗿", shortName: "COL. CADAV.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 7, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Alla morte genera 2 Carogne Rianimate nelle caselle adiacenti libere." },
  "Drago delle Fosse": { faction: "Ceneri", glyph: "🐉", shortName: "DRAGO FOSSE", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 6, move: "knight", gittata: 2, rarity: "M", isMiniature: true, desc: "Soffio di Cenere: Balzo a L; attacca a distanza 2 colpendo anche le caselle adiacenti al bersaglio." },
  "Banshee Regina": { faction: "Ceneri", glyph: "👑", shortName: "REGINA C.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 5, move: "diag2", gittata: 2, rarity: "R", isMiniature: true, desc: "Gittata 2 diagonale: sottrae 1 Sangue all'avversario ogni volta che danneggia un pezzo." },
  "Guerriero Eterno": { faction: "Ceneri", glyph: "💀", shortName: "ETERNO", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 5, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "La prima volta che muore ritorna in gioco con 2 PV sulla casella di partenza." },

  // SORTILEGI & REAZIONI (11)
  "Offerta Funebre": { faction: "Ceneri", glyph: "🕯️", shortName: "OFFERTA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Sacrifica una tua truppa a costo 1 per incassare 3 Segnalini Sangue e pescare 1 carta." },
  "Offerta d'Ossa": { faction: "Ceneri", glyph: "🦴", shortName: "OFFERTA OSSA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Sacrifica una truppa per pescare 2 carte e incassare 2 Segnalini Sangue." },
  "Marea Sepolcrale": { faction: "Ceneri", glyph: "💀", shortName: "SEPOLCRALE", cost: 2, bloodCost: 3, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Rianima 2 truppe a costo 1-2 dal Cimitero adiacenti al Comandante o ad Altari." },
  "Esplosione Spettrale": { faction: "Ceneri", glyph: "💥", shortName: "ESPL. SPETTR.", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Fai detonare un tuo Guscio o Carogna infliggendo 3 danni ad area ortogonale." },
  "Salasso di Massa": { faction: "Ceneri", glyph: "🩸", shortName: "SALASSO M.", cost: 2, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Tutte le unità in campo con salute inferiore a 3 PV subiscono 1 danno immediato." },
  "Patto della Pira": { faction: "Ceneri", glyph: "📜", shortName: "PATTO PIRA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Subisci 2 danni al Comandante per ottenere 3 Sangue e 1 Azione extra in questo turno." },
  "Catene di Braci": { faction: "Ceneri", glyph: "⛓️", shortName: "CATENE B.", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Immobilizza un pezzo nemico per 1 round; subisce 1 danno se tenta di attaccare." },
  "Rianimazione Veloce": { faction: "Ceneri", glyph: "⚡", shortName: "RIAN. VELOCE", cost: 1, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Rimetti in gioco una truppa a costo 1 morta in questo round conferendole Slancio." },
  "Festino Macabro": { faction: "Ceneri", glyph: "🍖", shortName: "FESTINO", cost: 2, bloodCost: 3, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Distruggi tutti i tuoi pezzi a costo 1: cura il tuo Comandante di 3 PV per ciascuno." },
  "Scudo di Brace": { faction: "Ceneri", glyph: "🔥", shortName: "SCUDO BRACE", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: alla morte di un alleato, infligge 2 danni immediati all'uccisore." },
  "Riflesso di Carne": { faction: "Ceneri", glyph: "🩸", shortName: "RIFLESSO", cost: 0, bloodCost: 3, type: "reaction", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Reazione: quando subisci danno, trasferisci 3 danni su una truppa nemica." },

  // =========================================================================
  // 3. FORGIA CIECA (38 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE (5)
  "Altare della Fornace Eterna": { faction: "Forgia", glyph: "🔥", shortName: "FORNACE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Quando subisce danno senza cadere, infligge 1 danno a tutte le unità adiacenti." },
  "Fornace della Tempra Eterna": { faction: "Forgia", glyph: "⚒️", shortName: "TEMPRA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Gli automi alleati che stazionano adiacenti all'Altare ottengono permanentemente +1 ATT." },
  "Blocco di Scorie Incandescenti": { faction: "Forgia", glyph: "🧱", shortName: "BLOCCO SCORIE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Può essere consumato come azione gratuita per ottenere 1 Mana immediato." },
  "Torre dei Fumi": { faction: "Forgia", glyph: "🏭", shortName: "TORRE FUMI", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Fumo denso: le unità entro 1 casella non possono essere bersagliate a distanza." },
  "Incudine Ancestrale": { faction: "Forgia", glyph: "🔨", shortName: "INCUDINE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 7, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Se distrutta conferisce +2 ATT a tutti gli automi alleati sul campo." },

  // FANTERIA 1M (6)
  "Rottame Semovente": { faction: "Forgia", glyph: "⚙️", shortName: "ROTTAME", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Macerie: alla morte lascia un Blocco di Scorie (0 ATT / 2 PV) sulla casella." },
  "Costrutto di Scorie": { faction: "Forgia", glyph: "🪨", shortName: "COSTRUTTO", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Recupero termico: lascia materiale di scarto per le abilità della Forgia." },
  "Ragno Meccanico": { faction: "Forgia", glyph: "🕷️", shortName: "RAGNO MEC.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "omni", gittata: 1, slancio: true, rarity: "C", isMiniature: true, desc: "Slancio Omnidirezionale: muove in ogni direzione e attacca subito." },
  "Servo di Bronzo": { faction: "Forgia", glyph: "🥉", shortName: "SERVO BRONZO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Riparatore: ripristina 1 PV a un automa alleato adiacente a inizio turno." },
  "Puntone Semovente": { faction: "Forgia", glyph: "🔩", shortName: "PUNTONE", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Presidio: blocca linee; contrattacca con 2 ATT se caricato frontalmente." },
  "Minatore Meccanico": { faction: "Forgia", glyph: "⛏️", shortName: "MINATORE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "[1 Azione]: distrugge un muro adiacente per generare +1 Mana temporaneo." },

  // SPECIALISTI 2-3M (11)
  "Fonditore di Piastre": { faction: "Forgia", glyph: "🔨", shortName: "FONDITORE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "[1 Azione]: infligge 2 danni a un Altare per donare +2 ATT / +1 PV a un alleato." },
  "Martellatore Meccanico": { faction: "Forgia", glyph: "🦾", shortName: "MARTELLAT.", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Battitura a caldo: quando attacca spinge il bersaglio (+2 danni se urta strutture)." },
  "Automa Rivettato": { faction: "Forgia", glyph: "🤖", shortName: "AUTOMA RIV.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Armatura termica: riduce di -1 i danni subiti da attacchi fisici in mischia." },
  "Balestriere a Vapore": { faction: "Forgia", glyph: "💨", shortName: "BAL. VAPORE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: spara a distanza 2 senza contrattacco; spinge il bersaglio di 1 casella." },
  "Trivellatore di Rovina": { faction: "Forgia", glyph: "🪛", shortName: "TRIVELLAT.", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 2, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Penetrazione: ignora armature e riduzioni passive del difensore." },
  "Centauro Meccanico": { faction: "Forgia", glyph: "🐎", shortName: "CENTAURO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: salta ostacoli; ottiene +1 ATT se attacca nello stesso turno in cui muove." },
  "Colatore di Ghisa": { faction: "Forgia", glyph: "🫗", shortName: "COLATORE", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: ricopre la casella colpita di metallo fuso (1 danno a chi vi sosta)." },
  "Automa Sentinella": { faction: "Forgia", glyph: "🛡️", shortName: "SENT. FORGIA", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Riflette 1 danno da mischia verso l'attaccante ogni volta che incassa un colpo." },
  "Demolitore Pneumatico": { faction: "Forgia", glyph: "⛏️", shortName: "DEMOLITORE", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Infligge 5 danni contro muri, blocchi e Altari nemici." },
  "Forgiatore di Scaglie": { faction: "Forgia", glyph: "🛠️", shortName: "FORG. SCAGLIE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "A inizio turno conferisce 1 Scudo temporaneo a un'unità amica adiacente." },
  "Saldatore di Rame": { faction: "Forgia", glyph: "🔥", shortName: "SALDATORE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Cura 2 PV a una struttura o automa alleato al costo di 1 Azione." },

  // COLOSSI 4+M (5)
  "Colosso di Scorie": { faction: "Forgia", glyph: "🗿", shortName: "COLOSSO", cost: 4, type: "unit", slot: "HEAVY", att: 4, pv: 6, move: "ortho2", gittata: 1, rarity: "R", isMiniature: true, desc: "Devastazione: il danno letale inflitto in eccesso travolge il pezzo retrostante." },
  "Fornace Semovente": { faction: "Forgia", glyph: "🏭", shortName: "FORN. SEMOV.", cost: 4, type: "unit", slot: "HEAVY", att: 2, pv: 7, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "[1 Azione]: consuma un Blocco per conferire +1 ATT a tutte le truppe entro 2 caselle." },
  "Golem di Bronzo Antico": { faction: "Forgia", glyph: "🥉", shortName: "GOLEM BRONZO", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 8, move: "ortho", gittata: 1, rarity: "M", isMiniature: true, desc: "Inarrestabile: riduce tutti i danni subiti di 1. Immune a spinte e trascinamenti." },
  "Cannone a Vapore": { faction: "Forgia", glyph: "💣", shortName: "CANNONE VAP.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 4, move: "ortho", gittata: 3, rarity: "R", isMiniature: true, desc: "Gittata 3: tiro d'assedio ad alto impatto. Se colpisce un Altare lo demolisce." },
  "Golia Meccanico": { faction: "Forgia", glyph: "🤖", shortName: "GOLIA MEC.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Alla morte genera 2 Rottami Semoventi nelle caselle libere ortogonali." },

  // SORTILEGI & REAZIONI (11)
  "Fusione d'Emergenza": { faction: "Forgia", glyph: "💥", shortName: "FUSIONE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Sacrifica un proprio Altare o Blocco per pescare 2 carte e infliggere 2 danni ad area." },
  "Fonderia da Campo": { faction: "Forgia", glyph: "🏭", shortName: "FONDERIA", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Converte un Muro in Blocco di Scorie e infligge 1 danno alle unità adiacenti." },
  "Ignizione Primordiale": { faction: "Forgia", glyph: "🔥", shortName: "IGNIZIONE", cost: 2, bloodCost: 3, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Trasforma un Altare in truppa semovente 4/5 mantenendo la produzione di Mana." },
  "Sovraccarico Termico": { faction: "Forgia", glyph: "⚡", shortName: "SOVRACCARICO", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Un automa ottiene +2 ATT per questo round, ma subisce 2 danni alla fine del turno." },
  "Riciclo Metalli": { faction: "Forgia", glyph: "♻️", shortName: "RICICLO", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Rimuovi un Blocco di Scorie per incassare immediatamente +2 Mana spendibili subito." },
  "Saldata d'Urgenza": { faction: "Forgia", glyph: "🧯", shortName: "SALDATA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Ripristina 3 PV a un automa alleato o al Comandante." },
  "Gettata di Ghisa": { faction: "Forgia", glyph: "🌋", shortName: "GETTATA", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Infligge 2 danni a un bersaglio e riduce il suo movimento a 0 per 1 round." },
  "Forgiatura Istantanea": { faction: "Forgia", glyph: "🔨", shortName: "FORG. ISTANT.", cost: 3, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Schiera immediatamente un automa a costo 1 o 2 dalla mano a costo 0 Azioni." },
  "Tempra d'Acciaio": { faction: "Forgia", glyph: "🛡️", shortName: "TEMPRA ACC.", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Conferisce +1 armatura permanente a un automa alleato (max 2 per unità)." },
  "Raffreddamento Istantaneo": { faction: "Forgia", glyph: "🧊", shortName: "RAFFREDD.", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: quando un Altare subisce danno letale, sopravvive a 1 PV diventando Blocco." },
  "Detonazione di Scorie": { faction: "Forgia", glyph: "💣", shortName: "DETON. SCORIE", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: fai esplodere un Blocco adiacente a un attaccante nemico infliggendogli 3 danni." },

  // =========================================================================
  // 4. MAREA ASTRALE (38 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE (5)
  "Fugace Condotto Astrale": { faction: "Marea", glyph: "🌌", shortName: "CONDOTTO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Gli attacchi a distanza nemici che transitano adiacenti all'Altare vengono deviati." },
  "Altare del Vuoto Astrale": { faction: "Marea", glyph: "🕳️", shortName: "VUOTO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. I nemici non possono entrare nelle 4 caselle ortogonali adiacenti muovendo in diagonale." },
  "Vortice Tellurico": { faction: "Marea", glyph: "🌀", shortName: "VORTICE TEL.", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. A fine turno trascina di 1 passo verso di sé il nemico più vicino entro 3 caselle." },
  "Prisma Stellare": { faction: "Marea", glyph: "💎", shortName: "PRISMA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Estende di +1 la gittata dei tiri a distanza delle unità amiche adiacenti." },
  "Pozzo di Gravità": { faction: "Marea", glyph: "⚓", shortName: "POZZO GRAV.", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Le truppe nemiche che tentano di allontanarsi da esso pagano +1 Azione di movimento." },

  // FANTERIA 1M (6)
  "Sonda di Singolarità": { faction: "Marea", glyph: "🛰️", shortName: "SONDA", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Campo repulsivo: devia i nemici che entrano nelle caselle ortogonalmente adiacenti." },
  "Scivolatore Astrale": { faction: "Marea", glyph: "⛸️", shortName: "SCIVOLATORE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Passo etereo: attraversa le caselle occupate da miniature alleate durante il movimento." },
  "Vedetta di Nebulosa": { faction: "Marea", glyph: "🔭", shortName: "VEDETTA NEB.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "diag", gittata: 2, rarity: "C", isMiniature: true, desc: "Gittata 2 diagonale: tiro rapido senza contrattacco lungo diagonali libere." },
  "Larva Eterea": { faction: "Marea", glyph: "🐛", shortName: "LARVA ET.", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 1, move: "diag2", gittata: 1, slancio: true, rarity: "C", isMiniature: true, desc: "Slancio: scatta di 2 passi diagonali e attacca subito nel turno di ingresso." },
  "Devia-Frecce Astrale": { faction: "Marea", glyph: "🧲", shortName: "DEVIA-FRECCE", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Immune a danni a distanza; contrattacca solo a bersagli che la colpiscono in mischia." },
  "Riflesso di Marea": { faction: "Marea", glyph: "🪞", shortName: "RIFLESSO M.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Scambia di posizione con un alleato adiacente quando viene ingaggiato." },

  // SPECIALISTI 2-3M (11)
  "Tessitore di Vortici": { faction: "Marea", glyph: "🕸️", shortName: "TESSITORE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "diag2", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2 diagonale: colpisce a distanza 2 e trascina il bersaglio di 1 casella verso di sé." },
  "Tessitore d'Ombre": { faction: "Marea", glyph: "🕷️", shortName: "TESS. OMBRE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "diag2", gittata: 2, rarity: "U", isMiniature: true, desc: "Tiro sfasante: se colpisce inverte la posizione del bersaglio con una casella libera." },
  "Corsaro delle Onde": { faction: "Marea", glyph: "⛵", shortName: "CORSARO", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 2, move: "diag2", gittata: 1, rarity: "C", isMiniature: true, desc: "Spostamento rapido: può scattare fino a 2 caselle diagonali prima di colpire." },
  "Mistico di Vespera": { faction: "Marea", glyph: "🔮", shortName: "MISTICO V.", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "diag", gittata: 2, rarity: "U", isMiniature: true, desc: "Ogni volta che trascina o sposta un nemico, gli infligge 1 danno da distorsione." },
  "Sferzatore Gravitazionale": { faction: "Marea", glyph: "🌊", shortName: "SFERZATORE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "omni", gittata: 2, rarity: "U", isMiniature: true, desc: "Spinge indietro di 2 caselle qualsiasi bersaglio che colpisce a distanza." },
  "Pungolatore Stellare": { faction: "Marea", glyph: "✨", shortName: "PUNGOLATORE", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: salta ostacoli; ignora riduzioni di danno e coperture." },
  "Danzatore dei Flussi": { faction: "Marea", glyph: "💃", shortName: "DANZATORE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "diag2", gittata: 1, rarity: "C", isMiniature: true, desc: "Schiva il primo attacco in mischia subito in ciascun round scambiandosi di casella." },
  "Arcanista di Flusso": { faction: "Marea", glyph: "🌀", shortName: "ARCANISTA", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "diag", gittata: 3, rarity: "R", isMiniature: true, desc: "Gittata 3 diagonale: tira a lunga distanza lungo assi diagonali liberi senza contrattacco." },
  "Medusa del Vuoto": { faction: "Marea", glyph: "🪼", shortName: "MEDUSA", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Stordimento: chi la colpisce in mischia non può muovere nel suo turno successivo." },
  "Nocchiero Celeste": { faction: "Marea", glyph: "🧭", shortName: "NOCCHIERO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho2", gittata: 1, rarity: "U", isMiniature: true, desc: "[1 Azione]: teletrasporta un alleato adiacente su una casella libera entro 2 passi." },
  "Scudiero di Corallo": { faction: "Marea", glyph: "🪸", shortName: "SCUD. CORALLO", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Ottiene +1 armatura se posizionato su una casella adiacente a un Altare." },

  // COLOSSI 4+M (5)
  "Sentinella dell'Eclissi": { faction: "Marea", glyph: "🌒", shortName: "SENTINELLA", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Freno: nemici che muovono adiacenti a lei spendono entrambe le loro 2 Azioni." },
  "Catapulta a Trazione": { faction: "Marea", glyph: "☄️", shortName: "CATAPULTA", cost: 4, type: "unit", slot: "HEAVY", att: 2, pv: 5, move: "diag", gittata: 4, rarity: "R", isMiniature: true, desc: "Gittata 4 diagonale: scaglia proiettili a distanza 4; raddoppia i danni contro Altari." },
  "Kraken di Nebulosa": { faction: "Marea", glyph: "🐙", shortName: "KRAKEN", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 7, move: "diag2", gittata: 2, rarity: "M", isMiniature: true, desc: "Trascina tutti i nemici entro raggio 2 verso di sé quando sferra un attacco." },
  "Leviatano dei Vuoti": { faction: "Marea", glyph: "🐋", shortName: "LEVIATANO", cost: 5, type: "unit", slot: "HEAVY", att: 3, pv: 8, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Occupa 1 casella ma proietta aura d'impatto: nemici adiacenti pagano +1 Mana per agire." },
  "Colosso d'Ossidiana Fluida": { faction: "Marea", glyph: "🗿", shortName: "COL. FLUIDO", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "diag2", gittata: 1, rarity: "C", isMiniature: true, desc: "Immune a danni da collisione; si sposta di 1 casella gratis se colpito da sortilegi." },

  // SORTILEGI & REAZIONI (11)
  "Singolarità Tascabile": { faction: "Marea", glyph: "🌌", shortName: "SINGOLARITA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Trascina una truppa nemica di 2 caselle in linea retta verso il Comandante." },
  "Pressione di Marea": { faction: "Marea", glyph: "🌊", shortName: "PRESSIONE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Trascina 2 unità nemiche qualsiasi di 1 casella verso l'asse centrale della scacchiera." },
  "Deviazione Astrale": { faction: "Marea", glyph: "🌀", shortName: "DEVIAZIONE", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: quando un nemico dichiara una mossa verso di te, devia la destinazione di 1 asse." },
  "Collasso di Marea": { faction: "Marea", glyph: "🌪️", shortName: "COLLASSO", cost: 2, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Nemici entro 2 passi da un proprio Altare subiscono 2 danni e vengono respinti." },
  "Spostamento di Fase": { faction: "Marea", glyph: "⚡", shortName: "FASE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Scambia istantaneamente di posizione 2 miniature amiche sulla plancia." },
  "Salto di Quanta": { faction: "Marea", glyph: "💫", shortName: "SALTO QUANTA", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Teletrasporta un'unità amica su una qualsiasi casella adiacente a un proprio Altare." },
  "Frattura Spazio-Temporale": { faction: "Marea", glyph: "🕳️", shortName: "FRATT. SPAZIO", cost: 2, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Rimuove dal gioco un'unità per 1 intero round; riappare al round dopo nella stessa casella." },
  "Ritorno all'Origine": { faction: "Marea", glyph: "↩️", shortName: "RITORNO", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Rimanda una miniatura nemica non-Comandante sulla sua riga di partenza (riga 8)." },
  "Marea Crescente": { faction: "Marea", glyph: "🌊", shortName: "CRESCENTE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Tutte le unità che muovono in diagonale ottengono +1 passo di movimento in questo round." },
  "Bolla di Vuoto": { faction: "Marea", glyph: "🫧", shortName: "BOLLA VUOTO", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: annulla un attacco contro un alleato e lo sposta di 1 casella diagonale." },
  "Barriera di Risonanza": { faction: "Marea", glyph: "🪞", shortName: "RISONANZA", cost: 0, bloodCost: 3, type: "reaction", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Reazione: respinge l'attaccante di 3 caselle in linea retta (+2 danni se urta ostacoli)." },

  // =========================================================================
  // 5. SILENZIO D'ORO (38 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE (5)
  "Monolito Giurato di Tassa": { faction: "Silenzio", glyph: "⚖️", shortName: "MONO. TASSA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Sanzione: se distrutto dal nemico, l'avversario perde 1 Azione nel suo turno successivo." },
  "Altare della Decima": { faction: "Silenzio", glyph: "📜", shortName: "DECIMA", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Anatema: se distrutto dal nemico, l'avversario perde 2 Mana a turno per 2 round." },
  "Sigillo di Marmo Bianco": { faction: "Silenzio", glyph: "🏛️", shortName: "SIG. MARMO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Finché è integro, l'avversario non può lanciare più di 1 sortilegio a turno." },
  "Pulpito della Regola": { faction: "Silenzio", glyph: "📖", shortName: "PULPITO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. I nemici che sostano entro 2 caselle da questo Altare non generano Sangue se muoiono." },
  "Obelisco dell'Indulto": { faction: "Silenzio", glyph: "🕊️", shortName: "INDULTO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Se sacrificato, rimuove tutte le alterazioni e penalità dalle tue unità." },

  // FANTERIA 1M (6)
  "Censore Minore": { faction: "Silenzio", glyph: "🔕", shortName: "CENSORE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Silenziatore: rimuove passive, armature e abilità speciali ai nemici adiacenti." },
  "Monaco del Voto": { faction: "Silenzio", glyph: "📜", shortName: "VOTO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Voto di fermezza: le unità nemiche adiacenti non possono ricevere aumenti di ATT o cure." },
  "Novizio della Regola": { faction: "Silenzio", glyph: "🕯️", shortName: "NOVIZIO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Contrattacca sempre a 2 ATT se il nemico attaccante possiede più di 2 Sangue." },
  "Scriba Inquisitore": { faction: "Silenzio", glyph: "✒️", shortName: "SCRIBA", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Quando muore fa scartare 1 carta casuale dalla mano dell'avversario." },
  "Sentinella Silente": { faction: "Silenzio", glyph: "🛡️", shortName: "SENT. SILENTE", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Presidio: blocca linee; contrattacca con 2 ATT solo se caricata direttamente." },
  "Portatore del Canone": { faction: "Silenzio", glyph: "⚖️", shortName: "PORTATORE C.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Gli alleati adiacenti non possono essere presi a bersaglio da magie nemiche a costo 1." },

  // SPECIALISTI 2-3M (11)
  "Arbitro di Pegni": { faction: "Silenzio", glyph: "🪙", shortName: "ARBITRO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Tassa di rappresaglia: se subisce danno sottrae 1 Sangue all'avversario." },
  "Inquisitore di Pegni": { faction: "Silenzio", glyph: "⚖️", shortName: "INQUISITORE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Tassa di Sangue: quando contrattacca con successo in mischia ruba 1 Sangue al nemico." },
  "Monaco Censore": { faction: "Silenzio", glyph: "📿", shortName: "M. CENSORE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Le truppe nemiche adiacenti pagano +1 Azione per muoversi via dalla sua casella." },
  "Custode delle Leggi": { faction: "Silenzio", glyph: "📜", shortName: "CUSTODE LEGGI", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Immune a sortilegi diretti; trasferisce la sua immunità alle strutture adiacenti." },
  "Giudice di Prima Istanza": { faction: "Silenzio", glyph: "🔨", shortName: "GIUDICE 1A", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Infligge 4 danni a pezzi nemici che non hanno ancora contrattaccato in questo round." },
  "Epuratore di Mana": { faction: "Silenzio", glyph: "✨", shortName: "EPURATORE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: colpisce a distanza riducendo di 1 il Mana del nemico per il round successivo." },
  "Penitente Incatenato": { faction: "Silenzio", glyph: "⛓️", shortName: "PENITENTE", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Non può muoversi a meno che il controllore non spenda 1 Sangue oltre all'Azione." },
  "Guardiano della Decima": { faction: "Silenzio", glyph: "💰", shortName: "GUARD. DECIMA", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: atterra sottraendo 1 Sangue al giocatore avversario se adiacente a un nemico." },
  "Paladino del Silenzio": { faction: "Silenzio", glyph: "🛡️", shortName: "PALADINO S.", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Armatura: -1 danno; non può essere scavalcato da movimenti a Balzo a L." },
  "Cerusico Giurato": { faction: "Silenzio", glyph: "🩹", shortName: "CERUSICO", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "[1 Azione]: cura 2 PV al Comandante o a un'unità amica spendendo 1 Sangue." },
  "Dogmatico di Ferro": { faction: "Silenzio", glyph: "📖", shortName: "DOGMATICO", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Scatta di 2 caselle ortogonali per colpire nemici che hanno accumulato Sangue." },

  // COLOSSI 4+M (5)
  "Esecutore della Decima": { faction: "Silenzio", glyph: "⚖️", shortName: "ESECUTORE", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 5, move: "knight", gittata: 1, rarity: "R", isMiniature: true, desc: "Sentenza: Balzo a L. Infligge 5 danni se il bersaglio ha già agito nel turno." },
  "Giustiziere Senza Volto": { faction: "Silenzio", glyph: "👤", shortName: "GIUSTIZIERE", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "knight", gittata: 1, rarity: "R", isMiniature: true, desc: "Castigo puro: Balzo a L; i suoi attacchi ignorano armature fisiche e coperture." },
  "Archivista Supremo": { faction: "Silenzio", glyph: "📚", shortName: "ARCHIVISTA", cost: 4, type: "unit", slot: "HEAVY", att: 2, pv: 7, move: "ortho", gittata: 2, rarity: "R", isMiniature: true, desc: "Gittata 2: blocca il lancio di sortilegi nemici entro 3 caselle attorno a sé." },
  "Colosso dell'Interdizione": { faction: "Silenzio", glyph: "🗿", shortName: "COL. INTERD.", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 8, move: "ortho", gittata: 1, rarity: "M", isMiniature: true, desc: "Tassa suprema: finché è in vita, l'avversario deve spendere 1 Mana extra per ogni attacco." },
  "Avatar del Giuramento": { faction: "Silenzio", glyph: "👼", shortName: "AVATAR GIUR.", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "Se distrutto, sigilla tutte le abilità attive del pezzo uccisore per il resto del match." },

  // SORTILEGI & REAZIONI (11)
  "Editto di Quarantena": { faction: "Silenzio", glyph: "🚫", shortName: "QUARANTENA", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Sigilla un'area 2x2 per 1 round: nessuna unità può entrarvi o attaccare attraverso." },
  "Editto di Confisca": { faction: "Silenzio", glyph: "📑", shortName: "CONFISCA ED.", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Sottrae 1 Mana dalla riserva iniziale dell'avversario nel suo turno successivo." },
  "Sigillo di Confisca": { faction: "Silenzio", glyph: "📜", shortName: "CONFISCA S.", cost: 1, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Sottrae 2 Sangue al nemico (infligge 2 danni al Comandante se a secco)." },
  "Interdizione di Legge": { faction: "Silenzio", glyph: "🔕", shortName: "INTERDIZIONE", cost: 0, bloodCost: 3, type: "reaction", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Reazione: annulla e dissipa completamente un sortilegio nemico appena lanciato." },
  "Manto del Giudizio": { faction: "Silenzio", glyph: "⚖️", shortName: "MANTO GIUD.", cost: 1, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Reazione su attacco a Comandante: nega il danno e sottrae 1 Azione al turno nemico." },
  "Tassa Imperiale": { faction: "Silenzio", glyph: "💰", shortName: "TASSA IMP.", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "L'avversario deve pagare 1 Sangue per ogni unità che muove nel suo prossimo turno." },
  "Anatema del Silenzio": { faction: "Silenzio", glyph: "🤐", shortName: "ANATEMA", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Rimuove permanentemente il testo di abilità di un'unità nemica non-Comandante." },
  "Confisca Forzata": { faction: "Silenzio", glyph: "🗝️", shortName: "CONFISCA FORZ.", cost: 2, bloodCost: 1, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Distrugge un Altare nemico se l'avversario controlla più Altari di te." },
  "Sentenza Inappellabile": { faction: "Silenzio", glyph: "🔨", shortName: "SENTENZA IN.", cost: 3, bloodCost: 3, type: "spell", slot: "SPELL", rarity: "R", isMiniature: false, desc: "Distrugge istantaneamente una truppa nemica che ha sferrato un attacco in questo round." },
  "Veto Inquisitorio": { faction: "Silenzio", glyph: "🛑", shortName: "VETO", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: nega l'attivazione di un Rito d'Armi o abilità [1 Azione] nemica." },
  "Giudizio Immediato": { faction: "Silenzio", glyph: "⚡", shortName: "GIUDIZIO IMM.", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: quando un nemico muove adiacente al Comandante, subisce 2 danni immediati." },

  // =========================================================================
  // 6. POOL NEUTRALE (100 CARTE)
  // =========================================================================
  // ALTARI & STRUTTURE NEUTRALI (10)
  "Altare": { faction: "Neutral", glyph: "🏛️", shortName: "ALTARE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana/turno. Struttura solida impassabile. Copertura: -1 danno fisico adiacenti." },
  "Vena Tettorica Instabile": { faction: "Neutral", glyph: "⚡", shortName: "VENA +2M", cost: 0, type: "altar", slot: "ALTAR", manaGen: 2, pv: 3, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+2 Mana/turno! Fragile (3 PV): se distrutto infligge 2 danni al Comandante alleato." },
  "Altare del Patto di Sangue": { faction: "Neutral", glyph: "🩸", shortName: "PATTO +2M", cost: 0, type: "altar", slot: "ALTAR", manaGen: 2, pv: 5, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+2 Mana/turno! Subisci 1 danno a inizio turno se incassi il secondo Mana." },
  "Il Cuore della Griglia": { faction: "Neutral", glyph: "💖", shortName: "CUORE +2M", cost: 0, type: "altar", slot: "ALTAR", manaGen: 2, pv: 8, att: 0, move: "none", gittata: 0, rarity: "M", isMiniature: false, isCenterOnly: true, desc: "Mitico: +2 Mana e +1 Sangue. Solo caselle centrali. Se sconfitto si converte al nemico!" },
  "Monolito dell'Eclissi Totale": { faction: "Neutral", glyph: "🌑", shortName: "ECLISSE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 6, att: 0, move: "none", gittata: 0, rarity: "M", isMiniature: false, desc: "+1 Mana. Tutti i sortilegi nemici costano +1 Mana addizionale finché è integro." },
  "Monolito di Basalto": { faction: "Neutral", glyph: "🪨", shortName: "BASALTO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 8, att: 0, move: "none", gittata: 0, rarity: "R", isMiniature: false, desc: "+1 Mana. Immune a sortilegi diretti nemici (non bersagliabile da Frantumare)." },
  "Pilastro delle Terre Aride": { faction: "Neutral", glyph: "🏜️", shortName: "PILASTRO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Fornisce copertura a 360 gradi alle unità amiche adiacenti." },
  "Sorgente Primordiale": { faction: "Neutral", glyph: "💧", shortName: "SORGENTE", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Rigenera 1 PV a inizio turno all'unità amica con meno salute adiacente." },
  "Altare dell'Assedio": { faction: "Neutral", glyph: "🏹", shortName: "ALT. ASSEDIO", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 5, att: 0, move: "none", gittata: 0, rarity: "U", isMiniature: false, desc: "+1 Mana. Le truppe con tiro a distanza adiacenti ottengono +1 danno contro Altari." },
  "Tomba Anonima": { faction: "Neutral", glyph: "🪦", shortName: "TOMBA ANON.", cost: 0, type: "altar", slot: "ALTAR", manaGen: 1, pv: 4, att: 0, move: "none", gittata: 0, rarity: "C", isMiniature: false, desc: "+1 Mana. Genera 1 Segnalino Sangue per chiunque la demolisca per primo." },

  // FANTERIA NEUTRALE 1M (20)
  "Recluta di Leva": { faction: "Neutral", glyph: "🗡️", shortName: "RECLUTA", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Fanteria economica per occupare le caselle chiave iniziali." },
  "Scudiero Rovinato": { faction: "Neutral", glyph: "🛡️", shortName: "SCUDIERO", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Presidio: non attacca attivamente; contrattacca solo se colpito." },
  "Ladro di Tombe": { faction: "Neutral", glyph: "🗝️", shortName: "LADRO", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Passo Diagonale: muove e attacca solo lungo le diagonali libere." },
  "Segugio Randagio": { faction: "Neutral", glyph: "🐺", shortName: "SEGUGIO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho2", gittata: 1, slancio: true, rarity: "C", isMiniature: true, desc: "Slancio: muove fino a 2 caselle ortogonali e attacca subito." },
  "Sentinella delle Mura": { faction: "Neutral", glyph: "🏰", shortName: "SENTINELLA", cost: 1, type: "unit", slot: "EARLY", att: 0, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Presidio: contrattacca a 2 ATT solo se ingaggiata in mischia." },
  "Schermagliatore Randagio": { faction: "Neutral", glyph: "🪓", shortName: "SCHERMAGL.", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "Unità multi-asse: muove di 1 casella in qualsiasi direzione." },
  "Mastino da Guerra": { faction: "Neutral", glyph: "🐕", shortName: "MASTINO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho2", gittata: 1, slancio: true, rarity: "C", isMiniature: true, desc: "Cacciatore rapido: muove fino a 2 caselle con Slancio." },
  "Tagliagole": { faction: "Neutral", glyph: "🔪", shortName: "TAGLIAGOLE", cost: 1, type: "unit", slot: "EARLY", att: 3, pv: 1, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Colpo letale: 3 ATT ma fragile con 1 solo punto vita." },
  "Disertore Reclutato": { faction: "Neutral", glyph: "🏃", shortName: "DISERTORE", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Muove di 1 casella gratis all'inizio della partita." },
  "Cacciatore di Ratti": { faction: "Neutral", glyph: "🪤", shortName: "CACC. RATTI", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "Ottiene +1 ATT se attacca unità con salute pari o inferiore a 2 PV." },
  "Strillone delle Strade": { faction: "Neutral", glyph: "📢", shortName: "STRILLONE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Alla morte rivela le prime 2 carte del mazzo nemico." },
  "Esploratore Cieco": { faction: "Neutral", glyph: "🦯", shortName: "ESPL. CIECO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "diag", gittata: 1, rarity: "C", isMiniature: true, desc: "Muove solo in diagonale; ignora la debolezza da schieramento." },
  "Minatore Randagio": { faction: "Neutral", glyph: "⛏️", shortName: "MINATORE R.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Infligge 3 danni contro strutture e barriere solide." },
  "Guerriero Tribale": { faction: "Neutral", glyph: "🪶", shortName: "TRIBALE", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 2, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "+1 ATT durante il contrattacco se combatte adiacente a un alleato." },
  "Cane da Pastore": { faction: "Neutral", glyph: "🐩", shortName: "PASTORE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Può saltare sopra una pedina alleata durante il movimento." },
  "Picchiere della Plebe": { faction: "Neutral", glyph: "🔱", shortName: "PICCA PLEBE", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Allungo economico: attacca a 2 caselle in linea retta senza contrattacco." },
  "Ragazzo di Trincea": { faction: "Neutral", glyph: "🧒", shortName: "RAGAZZO", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 2, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "Può scambiare posizione con una struttura adiacente a costo 1 Azione." },
  "Sentinella di Campagna": { faction: "Neutral", glyph: "🌾", shortName: "SENT. CAMP.", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Subisce -1 danno se posizionata nella propria metà campo." },
  "Mercenario a Giornata": { faction: "Neutral", glyph: "🪙", shortName: "MERC. GIORNO", cost: 1, type: "unit", slot: "EARLY", att: 2, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Costo economico ma non può contrattaccare se attaccato." },
  "Guida delle Paludi": { faction: "Neutral", glyph: "🗺️", shortName: "GUIDA PALUDI", cost: 1, type: "unit", slot: "EARLY", att: 1, pv: 3, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "Immune a Voragini e terreni dannosi sulla scacchiera." },

  // SPECIALISTI NEUTRALI 2-3M (35)
  "Mercenario Veterano": { faction: "Neutral", glyph: "⚔️", shortName: "VETERANO", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "omni", gittata: 1, rarity: "C", isMiniature: true, desc: "+1 ATT addizionale (3 ATT effettivi) durante il contrattacco." },
  "Giavellottiere Cieco": { faction: "Neutral", glyph: "🎯", shortName: "GIAVELLOT.", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 2, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Gittata 2 ortogonale: attacca a 2 caselle senza subire contrattacco." },
  "Arciere Cieco": { faction: "Neutral", glyph: "🏹", shortName: "ARCIERE C.", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Gittata 2 ortogonale: tiro a distanza lungo assi liberi." },
  "Esploratore delle Cripte": { faction: "Neutral", glyph: "🔦", shortName: "ESPL. CRIPTE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "knight", gittata: 1, rarity: "C", isMiniature: true, desc: "Balzo a L: salta ostacoli, truppe e Altari come il cavallo." },
  "Picchiere Mercenario": { faction: "Neutral", glyph: "🔱", shortName: "PICCA MERC.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Allungo: attacca a 2 caselle ortogonali senza contrattacco." },
  "Esploratore a Cavallo": { faction: "Neutral", glyph: "🐎", shortName: "ESPLORAT.", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo scacchistico a L: scavalca pezzi, ostacoli e Altari." },
  "Monaco Mendicante": { faction: "Neutral", glyph: "📿", shortName: "MONACO", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Elemosina: fa pescare 1 carta al controllore quando viene distrutto." },
  "Alchimista Dissidente": { faction: "Neutral", glyph: "🧪", shortName: "ALCHIMISTA", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "omni", gittata: 1, rarity: "U", isMiniature: true, desc: "Pozza tossica: alla morte avvelena la propria casella per 2 turni." },
  "Baluardo di Rovina": { faction: "Neutral", glyph: "🗿", shortName: "BALUARDO", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 6, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Ancorato al suolo: immune a spinte, trascinamenti e danni da urto." },
  "Balestriere d'Élite": { faction: "Neutral", glyph: "🏹", shortName: "BALESTR.", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 3, rarity: "U", isMiniature: true, desc: "Mira Fissa (Gittata 3): colpisce fino a 3 caselle ortogonali libere senza contrattacco." },
  "Spadaccino Errante": { faction: "Neutral", glyph: "🤺", shortName: "SPADACCINO", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "diag2", gittata: 1, rarity: "U", isMiniature: true, desc: "Duellante: infligge 4 danni se il bersaglio non ha alleati adiacenti." },
  "Lanciere a Cavallo": { faction: "Neutral", glyph: "🏇", shortName: "LANCIERE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "knight", gittata: 2, rarity: "U", isMiniature: true, desc: "Carica d'Allungo: Balzo a L e Gittata ortogonale 2 senza contrattacco." },
  "Custode del Tempio": { faction: "Neutral", glyph: "🏛️", shortName: "CUSTODE", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 6, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Baluardo mobile: alleati e Altari adiacenti subiscono -1 danno da attacchi." },
  "Duellante di Rovina": { faction: "Neutral", glyph: "⚔️", shortName: "DUELLANTE", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 4, move: "diag2", gittata: 1, rarity: "U", isMiniature: true, desc: "Maestro di Flanking: +2 danni se attacca con Aggiramento Tattico." },
  "Carrettiere da Trincea": { faction: "Neutral", glyph: "🛒", shortName: "CARRETTIERE", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Scorta protetta: quando muove traina un alleato adiacente nella casella liberata." },
  "Assassino di Tombe": { faction: "Neutral", glyph: "🗡️", shortName: "ASSASSINO", cost: 3, type: "unit", slot: "TACTIC", att: 4, pv: 2, move: "diag", gittata: 1, rarity: "U", isMiniature: true, desc: "Colpo invisibile: se attacca in diagonale, il bersaglio non contrattacca mai." },
  "Automa Disertore": { faction: "Neutral", glyph: "🤖", shortName: "AUTOMA", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 5, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Scudo arcano: annulla automaticamente il primo sortilegio nemico subito." },
  "Balestriere a Cavallo": { faction: "Neutral", glyph: "🏇", shortName: "BAL. CAVALLO", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "knight", gittata: 2, rarity: "U", isMiniature: true, desc: "Balzo a L & Gittata 2: salta ostacoli e tira a distanza ortogonale." },
  "Medico di Guerra": { faction: "Neutral", glyph: "💉", shortName: "MEDICO", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "[1 Azione]: cura 2 PV a un alleato adiacente." },
  "Bracconiere": { faction: "Neutral", glyph: "🏹", shortName: "BRACCONIERE", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 2, move: "ortho", gittata: 2, rarity: "C", isMiniature: true, desc: "Gittata 2: ottiene +1 ATT contro bestie o segugi." },
  "Ufficiale di Ventura": { faction: "Neutral", glyph: "🎖️", shortName: "UFFICIALE", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Le reclute e unità a costo 1 adiacenti ottengono +1 ATT." },
  "Spadaccino con Stocco": { faction: "Neutral", glyph: "🤺", shortName: "STOCCO", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 2, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Slancio lineare: scatta di 2 caselle in linea retta per attaccare." },
  "Tagliagole Esperto": { faction: "Neutral", glyph: "🔪", shortName: "TAGLIA. ESP.", cost: 3, type: "unit", slot: "TACTIC", att: 4, pv: 3, move: "omni", gittata: 1, rarity: "U", isMiniature: true, desc: "Infligge 5 danni se attacca alle spalle di un'unità già ingaggiata." },
  "Guardiano delle Porte": { faction: "Neutral", glyph: "🚪", shortName: "GUARD. PORTE", cost: 3, type: "unit", slot: "TACTIC", att: 1, pv: 6, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Immobilizza per 1 turno il primo nemico che muove adiacente a lui." },
  "Cavaliere Solitario": { faction: "Neutral", glyph: "🐎", shortName: "CAV. SOLITARIO", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 4, move: "knight", gittata: 1, rarity: "U", isMiniature: true, desc: "Balzo a L: ottiene +1 ATT se non ha alleati entro 2 caselle." },
  "Fanatico di Pietra": { faction: "Neutral", glyph: "🪨", shortName: "FANATICO P.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Immune a veleni e Voragini; non può essere spinto." },
  "Mago di Trincea": { faction: "Neutral", glyph: "🧙", shortName: "MAGO TRINCEA", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: il suo colpo infligge danno magico che ignora armature." },
  "Geniere Dissidente": { faction: "Neutral", glyph: "💣", shortName: "GENIERE DISS.", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "[1 Azione]: piazza una mina su una casella libera (2 danni a chi vi passa)." },
  "Ladro di Bestiame": { faction: "Neutral", glyph: "🐂", shortName: "LADRO BEST.", cost: 2, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho2", gittata: 1, rarity: "C", isMiniature: true, desc: "Ruba 1 Sangue all'avversario se distrugge una bestia o segugio." },
  "Veterano Sfregiato": { faction: "Neutral", glyph: "🪓", shortName: "VET. SFREG.", cost: 3, type: "unit", slot: "TACTIC", att: 3, pv: 5, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Contrattacca sempre, anche se il colpo subito è letale." },
  "Schermagliatore con Rete": { faction: "Neutral", glyph: "🕸️", shortName: "RETE", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 3, move: "omni", gittata: 2, rarity: "U", isMiniature: true, desc: "Gittata 2: intrappola il bersaglio impedendogli di muoversi per 1 round." },
  "Arciere Scelto": { faction: "Neutral", glyph: "🏹", shortName: "ARCIERE SC.", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "ortho", gittata: 3, rarity: "U", isMiniature: true, desc: "Gittata 3 ortogonale libera senza subire contrattacco." },
  "Cavalcagrifi": { faction: "Neutral", glyph: "🦅", shortName: "CAVALCAGRIFI", cost: 3, type: "unit", slot: "TACTIC", att: 2, pv: 3, move: "diag2", gittata: 1, slancio: true, rarity: "R", isMiniature: true, desc: "Slancio e volo: scavalca ostacoli muovendo di 2 passi diagonali." },
  "Lottatore delle Fosse": { faction: "Neutral", glyph: "🥊", shortName: "LOTTATORE", cost: 2, type: "unit", slot: "TACTIC", att: 3, pv: 3, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Spinge indietro di 1 casella qualsiasi bersaglio che colpisce in mischia." },
  "Chierico Errante": { faction: "Neutral", glyph: "✝️", shortName: "CHIERICO", cost: 2, type: "unit", slot: "TACTIC", att: 1, pv: 4, move: "ortho", gittata: 1, rarity: "U", isMiniature: true, desc: "Quando muore cura 3 PV al Comandante alleato." },

  // COLOSSI NEUTRALI 4+M (15)
  "Golia di Rifiuti": { faction: "Neutral", glyph: "🦾", shortName: "GOLIA", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 5, move: "ortho2", gittata: 1, rarity: "R", isMiniature: true, desc: "Frantumatore: danni raddoppiati (6 danni base) contro Altari e strutture." },
  "Cavaliere Senz'Armi": { faction: "Neutral", glyph: "🛡️", shortName: "CAVALIERE", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 4, move: "knight", gittata: 1, rarity: "R", isMiniature: true, desc: "Fendente d'Urto: Balzo a L; infligge 1 danno ad area ai nemici all'atterraggio." },
  "Guardiano dell'Archivio": { faction: "Neutral", glyph: "📜", shortName: "GUARDIANO", cost: 4, type: "unit", slot: "HEAVY", att: 1, pv: 7, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Tassa: nemici adiacenti pagano +1 Mana per attivare abilità con Azioni." },
  "Balista da Campo": { faction: "Neutral", glyph: "🎯", shortName: "BALISTA", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 4, move: "ortho", gittata: 3, rarity: "R", isMiniature: true, desc: "Gittata 3 ortogonale libera senza subire contrattacco difensivo." },
  "Veterano di Mille Assedi": { faction: "Neutral", glyph: "🎖️", shortName: "VET. ASSEDI", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Contrattacco letale: infligge +2 ATT addizionali (5 ATT) in contrattacco." },
  "Juggernaut di Rifiuti": { faction: "Neutral", glyph: "🚜", shortName: "JUGGERNAUT", cost: 4, type: "unit", slot: "HEAVY", att: 4, pv: 6, move: "ortho2", gittata: 1, rarity: "R", isMiniature: true, desc: "Travolgere: spinge indietro il pezzo colpito e occupa la sua casella." },
  "Colosso di Rame": { faction: "Neutral", glyph: "🥉", shortName: "COL. RAME", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 7, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Monolito vivente: genera anche +1 Mana a inizio turno finché è in vita." },
  "Titano di Basalto": { faction: "Neutral", glyph: "🏔️", shortName: "TITANO", cost: 5, type: "unit", slot: "HEAVY", att: 4, pv: 8, move: "ortho", gittata: 1, rarity: "M", isMiniature: true, desc: "Inamovibile: demolisce muri al passaggio; immune a spinte e voragini." },
  "Gigante delle Rocce": { faction: "Neutral", glyph: "🪨", shortName: "GIGANTE R.", cost: 5, type: "unit", slot: "HEAVY", att: 5, pv: 7, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Spazza via: quando colpisce in mischia danneggia anche le caselle ai fianchi." },
  "Mangiatore di Uomini": { faction: "Neutral", glyph: "👹", shortName: "OGRE", cost: 4, type: "unit", slot: "HEAVY", att: 4, pv: 5, move: "ortho", gittata: 1, rarity: "C", isMiniature: true, desc: "Forza bruta: attacca con 4 ATT ma subisce +1 danno da attacchi a distanza." },
  "Catapulta a Molla": { faction: "Neutral", glyph: "🪵", shortName: "CATAPULTA M.", cost: 4, type: "unit", slot: "HEAVY", att: 2, pv: 4, move: "ortho", gittata: 3, rarity: "U", isMiniature: true, desc: "Gittata 3: infligge 4 danni a strutture e barriere." },
  "Behemoth Corazzato": { faction: "Neutral", glyph: "🦣", shortName: "BEHEMOTH", cost: 5, type: "unit", slot: "HEAVY", att: 3, pv: 9, move: "ortho", gittata: 1, rarity: "R", isMiniature: true, desc: "Armatura pesante: riduce di -1 ogni danno subito da qualsiasi fonte." },
  "Rinoceronte d'Assedio": { faction: "Neutral", glyph: "🦏", shortName: "RINOCERONTE", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 6, move: "ortho2", gittata: 1, rarity: "U", isMiniature: true, desc: "Carica: infligge +2 danni se muove di 2 caselle prima di attaccare." },
  "Manticora Selvatica": { faction: "Neutral", glyph: "🦁", shortName: "MANTICORA", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 4, move: "knight", gittata: 2, rarity: "R", isMiniature: true, desc: "Balzo a L e spina velenosa a distanza 2 ortogonale senza contrattacco." },
  "Condottiero Senza Corona": { faction: "Neutral", glyph: "👑", shortName: "CONDOTTIERO", cost: 4, type: "unit", slot: "HEAVY", att: 3, pv: 5, move: "omni", gittata: 1, rarity: "R", isMiniature: true, desc: "Tutti gli alleati entro 2 caselle ottengono +1 ATT." },

  // SORTILEGI & REAZIONI NEUTRALI (20)
  "Frantumare la Pietra": { faction: "Neutral", glyph: "🔨", shortName: "FRANTUMA", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Distrugge istantaneamente 1 Altare o Muro nemico entro 4 caselle dal Comandante." },
  "Marcia Forzata": { faction: "Neutral", glyph: "⚡", shortName: "MARCIA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Muove 1 truppa alleata di 1 casella ortogonale extra a costo 0 Azioni." },
  "Carica Sfondante": { faction: "Neutral", glyph: "🦏", shortName: "CARICA SF.", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Muove un'unità di 1 passo extra e le conferisce +1 ATT sul prossimo attacco." },
  "Salasso Crudele": { faction: "Neutral", glyph: "🩸", shortName: "SALASSO", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "3 danni diretti a un'unità ferita o a costo <= 2 entro 3 caselle." },
  "Barricata Improvvisata": { faction: "Neutral", glyph: "🧱", shortName: "BARRICATA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Evoca un Muro di Detriti solido (0 ATT / 3 PV) su una casella libera entro 3 passi." },
  "Sguardo del Monolito": { faction: "Neutral", glyph: "👁️", shortName: "SGUARDO", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Blocca completamente movimento e attacchi di un nemico fino al prossimo turno." },
  "Pozza di Sangue": { faction: "Neutral", glyph: "🩸", shortName: "POZZA SANGUE", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Incanta una casella: chiunque vi transiti conferisce 2 Sangue al controllore." },
  "Genio del Geniere": { faction: "Neutral", glyph: "🔧", shortName: "GENIERE", cost: 2, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Ripristina 3 PV a un Altare o Muro alleato entro 3 passi dal Comandante." },
  "Rito di Comunione": { faction: "Neutral", glyph: "🍷", shortName: "COMUNIONE", cost: 3, bloodCost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Pesca 2 carte (3 carte se il tuo Comandante ha meno di 10 PV rimasti)." },
  "Furia dei Relitti": { faction: "Neutral", glyph: "💥", shortName: "FURIA REL.", cost: 3, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Danni diretti pari alle unità morte in questo round a una truppa entro 3 passi." },
  "Spaccatura Terrestre": { faction: "Neutral", glyph: "🌋", shortName: "SPACCATURA", cost: 2, bloodCost: 1, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Crea una Voragine permanente e impassabile su una casella libera entro 3 passi." },
  "Fendenti Incrociati": { faction: "Neutral", glyph: "⚔️", shortName: "FENDENTI", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Per questo turno, tutti gli attacchi con Flanking infliggono +2 danni extra." },
  "Giuramento Ancestrale": { faction: "Neutral", glyph: "👑", shortName: "GIURAMENTO", cost: 3, bloodCost: 3, type: "spell", slot: "SPELL", rarity: "M", isMiniature: false, desc: "Pesca 3 carte dal Grimorio e rigenera 4 PV al tuo Comandante." },
  "Contro-Urto": { faction: "Neutral", glyph: "🛡️", shortName: "CONTRO-URTO", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione su attacco mischia: riduce di 2 il danno e respinge l'attaccante (+2 danni urto)." },
  "Tagliola da Campo": { faction: "Neutral", glyph: "🪤", shortName: "TAGLIOLA", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Piazza una trappola invisibile: il primo nemico che vi entra subisce 2 danni e si ferma." },
  "Passo Falso": { faction: "Neutral", glyph: "🦶", shortName: "PASSO FALSO", cost: 0, bloodCost: 2, type: "reaction", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Reazione: quando un nemico dichiara una mossa, riduci il suo movimento a 0 per il round." },
  "Rinvigorire": { faction: "Neutral", glyph: "🧪", shortName: "RINVIGORIRE", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Un'unità alleata che ha già agito in questo round può muovere di 1 casella extra." },
  "Saccheggio Rapido": { faction: "Neutral", glyph: "💰", shortName: "SACCHEGGIO", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Se hai distrutto una struttura nemica in questo round, incassi +2 Mana immediati." },
  "Nebbia di Guerra": { faction: "Neutral", glyph: "🌫️", shortName: "NEBBIA", cost: 2, type: "spell", slot: "SPELL", rarity: "U", isMiniature: false, desc: "Tutti gli attacchi a distanza sono impediti per 1 intero round di gioco." },
  "Provocazione": { faction: "Neutral", glyph: "🗣️", shortName: "PROVOCAZ.", cost: 1, type: "spell", slot: "SPELL", rarity: "C", isMiniature: false, desc: "Costringe una truppa nemica entro 2 caselle ad attaccare l'alleato bersaglio nel suo turno." }
};